//
// Created by David on 29/04/2018.
//

#ifndef INC_2DGAMEFRAMEWORK_C_PLAYERMOVESTATE_HH
#define INC_2DGAMEFRAMEWORK_C_PLAYERMOVESTATE_HH


class C_PlayerMoveState {

};


#endif //INC_2DGAMEFRAMEWORK_C_PLAYERMOVESTATE_HH
