//
// Created by David on 29/04/2018.
//

#ifndef INC_2DGAMEFRAMEWORK_C_PLAYERNEUTRALSTATE_HH
#define INC_2DGAMEFRAMEWORK_C_PLAYERNEUTRALSTATE_HH


class C_PlayerNeutralState {

};


#endif //INC_2DGAMEFRAMEWORK_C_PLAYERNEUTRALSTATE_HH
